### PR TITLE
add visualizations

### LINKED ISSUE #28: add vizualizations of outputs
Add visualizations of the connectivity matrix potentially as a circle graph with stronger connections between ROIs having thicker lines.

### PR DESCRIPTION
**Pull request by amandakeasson**
## Summary

Fixes #28 . 

## List of changes proposed in this PR (pull-request)
* add visualizations of functional connectivity using the plot_connectivity_circle function

### CODE REVIEW

**Comment by jdkent** [comment]
Hi @amandakeasson, sorry I've been absent for so long, but I'm ready to start working on this pull request whenever you are. If you don't have time, just let me know and I'll take it over.

**Comment by amandakeasson** [comment]
Hi @jdkent, no problem! I have some time to work on this.

**Comment by amandakeasson** [comment]
Hi @jdkent - sorry for not getting to this until now. I fixed the errors from the TravisCI tests, so please let me know what I can do next!

(eventually I should change "title" and "outfile" variables - they're currently hard-coded as "example connectivity circle" and "example_connectivity_circle.jpg")

**Comment by amandakeasson** [comment]
Hi @jdkent, I made the requested changes, but there's an error that came up in bids.py:

`src/nibetaseries/interfaces/bids.py:13:6: W605 invalid escape sequence '\/'
src/nibetaseries/interfaces/bids.py:19:6: W605 invalid escape sequence '\/'`

How can I fix this?

Thanks! :)

**Comment by jdkent** [comment]
Everything is looking good so far!

The next step is to connect the output the interface now creates to the rest of the workflow.
Here are the items that should be completed (in no particular order):
- [add documentation here about this output figure](https://github.com/HBClab/NiBetaSeries/blob/ab04c1e9d3f83ccc2d7e7009838affa0fa27e4a6/src/nibetaseries/workflows/analysis.py#L46)
- add an output for the figure in [analysis.py](https://github.com/HBClab/NiBetaSeries/blob/ab04c1e9d3f83ccc2d7e7009838affa0fa27e4a6/src/nibetaseries/workflows/analysis.py#L73)
- connect `atlas_corr_node` to output node with the [interface figure output](https://github.com/HBClab/NiBetaSeries/blob/ab04c1e9d3f83ccc2d7e7009838affa0fa27e4a6/src/nibetaseries/workflows/analysis.py#L83)
- [create datasink interface for the figure output](https://github.com/HBClab/NiBetaSeries/blob/ab04c1e9d3f83ccc2d7e7009838affa0fa27e4a6/src/nibetaseries/workflows/base.py#L233)
- [connect the datasink interface to the workflow](https://github.com/HBClab/NiBetaSeries/blob/ab04c1e9d3f83ccc2d7e7009838affa0fa27e4a6/src/nibetaseries/workflows/base.py#L253)
- add mne and matplotlib to `install_requires` in [setup.py](https://github.com/HBClab/NiBetaSeries/blob/ab04c1e9d3f83ccc2d7e7009838affa0fa27e4a6/setup.py#L63)

**Pull request closed without merging**
