### PR TITLE
[DOC] Added zenodo file

### LINKED ISSUE #59: Add .zenodo.json
**Is your feature request related to a problem? Please describe.**
since we've recently added zenodo, we should add the .zenodo.json file to track contributors over time.

**Describe the solution you'd like**
add a .zenodo.json like in [fmriprep](https://github.com/poldracklab/fmriprep/blob/master/.zenodo.json)

**Describe alternatives you've considered**
There are no alternatives :smiling_imp: 

**Additional context**
here will be my entry in the `.zenodo.json` file:
```
 {
      "name": "Kent, James D.",
      "affiliation": "Neuroscience Program, University of Iowa",
      "orcid": "0000-0002-4892-2659"
    },
```

### PR DESCRIPTION
**Pull request by ctoroserey**
## Summary
Added the zenodo.json file (used the fmriprep one as ref), including info on the top 3 contributors. Happy to expand this list with the complete current list of contributors if you want. Couldn't run tox due to install issues on my end.

Fixes #59. 

## List of changes proposed in this PR (pull-request)
I suggest what James suggested when creating the issue.

### CODE REVIEW

**Comment by jdkent** [comment]
If you have the time to add all the contributors, I would be very appreciative, otherwise I can do it.

I think to fix the test, you just need to add `include *.json` in `MANIFEST.in`, hopefully that will fix the other error too.

**Comment by ctoroserey** [comment]
Sure, on it!

**Comment by jdkent** [comment]
There was an odd error with `coverage`, I push a commit to attempt to fix it, so we will see if the fix works. Thanks for your work on this!

**Comment by jdkent** [comment]
Aww, Thanks @KirstieJane!

**Comment by ctoroserey** [comment]
You're too kind @KirstieJane!

**Pull request merged**
