### PR TITLE
[ENH] Separate other conditions in LSS model

### LINKED ISSUE #86: Measure beta series homogeniety within region of interest
**Is your feature request related to a problem? Please describe.**
I don't know whether a given parcellation scheme worked for the data, and it would be nice to have a number that summarizes the homogeneity of the roi.

**Describe the solution you'd like**
I could take the first PCA component of each ROI and see how much variance in the roi is explained by the first component. Then each roi will have a % associated with it (higher meaning more homogeneous?) 

**Describe alternatives you've considered**
Another way is to take the average correlation of the region and correlate it with each voxel. Then take the average of voxelwise correlations (higher meaning more homogeneous)

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by tsalo**
## Summary

Fixes #86.

I haven't had a chance to use the development environment. ~~`test_base.py` fails locally when I run `tox`, but I can't figure out why. The change is minor so I assume that the tests will pass in CI.~~

## List of changes proposed in this PR (pull-request)

- Retain original trial types for all conditions, but rename all trials from the same conditions as the target trial to "other".

### CODE REVIEW

**Comment by jdkent** [comment]
Thank you so much @tsalo, I'm doing some refactoring of how I read/write bids data right now, so that most likely has an impact on the types of errors you're getting. As soon as I wrap that up, I'll see if that impacts the error message you're getting.

**Comment by tsalo** [comment]
@jdkent The error was happening when it started plotting correlation matrices, I think. It went away after I replaced `[trial_type]_original` with `other` for the non-target trials from the same trial type.

**Comment by tsalo** [comment]
Now that tests are passing, I think I just need to update relevant documentation that describes the original version of LSS.

**Comment by tsalo** [comment]
@jdkent Okay, I've updated the documentation regarding the description of LSS. The one thing I didn't update was the example LSS code, because I didn't know the best way to do that. Based on b99dcd0b0e39bd30f17fbb0dd1be96c198a364c2, I also changed "betaseries" to "beta series" through the document, but I can revert that if you want.

**Pull request merged**
